image: node:latest

stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  script:
    - npm run test

build_ios_job:
  stage: build
  script:
    - npm run build-ios

build_android_job:
  stage: build
  script:
    - npm run build-android

deploy_job:
  stage: deploy
  script:
    - npm run deploy
  only:
    - main
